Otus: homework_05::ConsoleComponentHelper Class Reference
homework_05::ConsoleComponentHelper Class Reference
Static Public Member Functions
static ConsoleToolsetPtr CastConsoleToolset (ToolsetWeakPtr toolset)
template<typename T >
static std::shared_ptr< T > CastComponent (ComponentWeakPtr component)
Detailed Description
Definition at line 13 of file console_component_handler.cpp.
Member Function Documentation
CastComponent()
template<typename T > static std::shared_ptr< T > homework_05::ConsoleComponentHelper::CastComponent (ComponentWeakPtr component) inline static
Definition at line 23 of file console_component_handler.cpp.
{
    std::shared_ptr<T> casted_component = std::static_pointer_cast<T>(component.lock());
    assert(casted_component);
    return casted_component;
  }
CastConsoleToolset()
static ConsoleToolsetPtr homework_05::ConsoleComponentHelper::CastConsoleToolset (ToolsetWeakPtr toolset) inline static
Definition at line 15 of file console_component_handler.cpp.
{
    auto console_toolset = std::static_pointer_cast<ConsoleToolset>(toolset.lock());
    assert(console_toolset);
    return console_toolset;
  }
Referenced by homework_05::ConsoleNameComponentHandler::DrawProperties(), homework_05::ConsoleCoordinate2DComponentHandler::DrawProperties(), homework_05::ConsoleCircleComponentHandler::DrawProperties(), homework_05::ConsoleRectangleComponentHandler::DrawProperties(), homework_05::ConsoleNameComponentHandler::SetProperties(), homework_05::ConsoleCoordinate2DComponentHandler::SetProperties(), homework_05::ConsoleCircleComponentHandler::SetProperties(), and homework_05::ConsoleRectangleComponentHandler::SetProperties().
The documentation for this class was generated from the following file:
homework-05/console_component_handler.cpp