Otus: homework_06::Matrix< T, DefaulValue, Dimension > Class Template Reference
homework_06::Matrix< T, DefaulValue, Dimension > Class Template Reference
#include <matrix.hpp>
Public Types
using type_declarator = TypeDeclarator< T, DefaulValue, Dimension >
using matrix_holder_type = typename MatrixHolder< T, DefaulValue, Dimension, 0 >::sub_holder_type
using matrix_holder_view_type = typename matrix_holder_type::value_holder_view_type
using iterator = MatrixIterator< T, DefaulValue, Dimension >
using const_iterator = MatrixConstIterator< T, DefaulValue, Dimension >
Public Types inherited from homework_06::TypeDeclarator< T, DefaulValue, Dimension >
using value_type = T
using matrix_type = Matrix< T, DefaulValue, Dimension >
using index_type = std::array< std::size_t, kDimension >
Public Member Functions
std::size_t size () const
matrix_holder_view_type operator[] (std::size_t key)
void set (const typename type_declarator::index_type &index, const T &value)
void set (const typename type_declarator::index_type &index, T &&value)
T get (const typename type_declarator::index_type &index) const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
Public Attributes
friend iterator
friend const_iterator
Private Member Functions
bool get_next_index (typename type_declarator::index_type &index) const
Private Attributes
std::size_t size_ = 0
matrix_holder_type matrix_holder_
Additional Inherited Members
Static Public Attributes inherited from homework_06::TypeDeclarator< T, DefaulValue, Dimension >
static constexpr T kDefaultValue = DefaulValue
static constexpr std::size_t kDimension = Dimension
Detailed Description
template<typename T, T DefaulValue = 0, std::size_t Dimension = 2>
class homework_06::Matrix< T, DefaulValue, Dimension >
Definition at line 488 of file matrix.hpp.
Member Typedef Documentation
const_iterator
template<typename T , T DefaulValue = 0, std::size_t Dimension = 2> using homework_06::Matrix< T, DefaulValue, Dimension >::const_iterator = MatrixConstIterator<T, DefaulValue, Dimension>
Definition at line 494 of file matrix.hpp.
iterator
template<typename T , T DefaulValue = 0, std::size_t Dimension = 2> using homework_06::Matrix< T, DefaulValue, Dimension >::iterator = MatrixIterator<T, DefaulValue, Dimension>
Definition at line 493 of file matrix.hpp.
matrix_holder_type
template<typename T , T DefaulValue = 0, std::size_t Dimension = 2> using homework_06::Matrix< T, DefaulValue, Dimension >::matrix_holder_type = typename MatrixHolder<T, DefaulValue, Dimension, 0>::sub_holder_type
Definition at line 491 of file matrix.hpp.
matrix_holder_view_type
template<typename T , T DefaulValue = 0, std::size_t Dimension = 2> using homework_06::Matrix< T, DefaulValue, Dimension >::matrix_holder_view_type = typename matrix_holder_type::value_holder_view_type
Definition at line 492 of file matrix.hpp.
type_declarator
template<typename T , T DefaulValue = 0, std::size_t Dimension = 2> using homework_06::Matrix< T, DefaulValue, Dimension >::type_declarator = TypeDeclarator<T, DefaulValue, Dimension>
Definition at line 490 of file matrix.hpp.
Member Function Documentation
begin() [1/2]
template<typename T , T DefaulValue = 0, std::size_t Dimension = 2> iterator homework_06::Matrix< T, DefaulValue, Dimension >::begin () inline
Definition at line 529 of file matrix.hpp.
                   {
    typename type_declarator::index_type index = { 0 };
    if (matrix_holder_.get_first_index(index)) {
      return iterator(this, std::move(index));
    }
    return end();
  }
begin() [2/2]
template<typename T , T DefaulValue = 0, std::size_t Dimension = 2> const_iterator homework_06::Matrix< T, DefaulValue, Dimension >::begin () const inline
Definition at line 542 of file matrix.hpp.
{
    typename type_declarator::index_type index = { 0 };
    if (matrix_holder_.get_first_index(index)) {
      return const_iterator(this, std::move(index));
    }
    return end();
  }
end() [1/2]
template<typename T , T DefaulValue = 0, std::size_t Dimension = 2> iterator homework_06::Matrix< T, DefaulValue, Dimension >::end () inline
Definition at line 538 of file matrix.hpp.
                 {
    return iterator(nullptr, typename type_declarator::index_type());
  }
Referenced by homework_06::Matrix< T, DefaulValue, Dimension >::begin(), and homework_06::Matrix< T, DefaulValue, Dimension >::begin().
end() [2/2]
template<typename T , T DefaulValue = 0, std::size_t Dimension = 2> const_iterator homework_06::Matrix< T, DefaulValue, Dimension >::end () const inline
Definition at line 551 of file matrix.hpp.
{
    return const_iterator(nullptr, typename type_declarator::index_type());
  }
get()
template<typename T , T DefaulValue = 0, std::size_t Dimension = 2> T homework_06::Matrix< T, DefaulValue, Dimension >::get (const typename type_declarator::index_type & index) const inline
Definition at line 525 of file matrix.hpp.
{
    return matrix_holder_.get(index);
  }
Referenced by homework_06::ValueHolder< T, DefaulValue, Dimension >::ValueHolderView::operator T(), homework_06::MatrixIterator< T, DefaulValue, Dimension >::operator*(), and homework_06::MatrixConstIterator< T, DefaulValue, Dimension >::operator*().
get_next_index()
template<typename T , T DefaulValue = 0, std::size_t Dimension = 2> bool homework_06::Matrix< T, DefaulValue, Dimension >::get_next_index (typename type_declarator::index_type & index) const inline private
Definition at line 556 of file matrix.hpp.
{
    return matrix_holder_.get_next_index(index);
  }
Referenced by homework_06::MatrixIterator< T, DefaulValue, Dimension >::operator++(), homework_06::MatrixConstIterator< T, DefaulValue, Dimension >::operator++(), homework_06::MatrixIterator< T, DefaulValue, Dimension >::operator++(), and homework_06::MatrixConstIterator< T, DefaulValue, Dimension >::operator++().
operator[]()
template<typename T , T DefaulValue = 0, std::size_t Dimension = 2> matrix_holder_view_type homework_06::Matrix< T, DefaulValue, Dimension >::operator[] (std::size_t key) inline
Definition at line 503 of file matrix.hpp.
{
    return matrix_holder_.at(*this, key);
  }
set() [1/2]
template<typename T , T DefaulValue = 0, std::size_t Dimension = 2> void homework_06::Matrix< T, DefaulValue, Dimension >::set (const typename type_declarator::index_type & index, const T & value) inline
Definition at line 507 of file matrix.hpp.
{
    auto diff = matrix_holder_.set(index, value);
    if (diff > 0) {
      ++size_;
    } else if (diff < 0) {
      --size_;
    }
  }
Referenced by homework_06::ValueHolder< T, DefaulValue, Dimension >::ValueHolderView::operator=(), and homework_06::ValueHolder< T, DefaulValue, Dimension >::ValueHolderView::operator=().
set() [2/2]
template<typename T , T DefaulValue = 0, std::size_t Dimension = 2> void homework_06::Matrix< T, DefaulValue, Dimension >::set (const typename type_declarator::index_type & index, T && value) inline
Definition at line 516 of file matrix.hpp.
{
    auto diff = matrix_holder_.set(index, std::forward<T>(value));
    if (diff > 0) {
      ++size_;
    } else if (diff < 0) {
      --size_;
    }
  }
size()
template<typename T , T DefaulValue = 0, std::size_t Dimension = 2> std::size_t homework_06::Matrix< T, DefaulValue, Dimension >::size () const inline
Definition at line 499 of file matrix.hpp.
{
    return size_;
  }
Referenced by main().
Member Data Documentation
const_iterator
template<typename T , T DefaulValue = 0, std::size_t Dimension = 2> friend homework_06::Matrix< T, DefaulValue, Dimension >::const_iterator
Definition at line 497 of file matrix.hpp.
iterator
template<typename T , T DefaulValue = 0, std::size_t Dimension = 2> friend homework_06::Matrix< T, DefaulValue, Dimension >::iterator
Definition at line 496 of file matrix.hpp.
matrix_holder_
template<typename T , T DefaulValue = 0, std::size_t Dimension = 2> matrix_holder_type homework_06::Matrix< T, DefaulValue, Dimension >::matrix_holder_ private
Definition at line 560 of file matrix.hpp.
Referenced by homework_06::Matrix< T, DefaulValue, Dimension >::begin(), homework_06::Matrix< T, DefaulValue, Dimension >::begin(), homework_06::Matrix< T, DefaulValue, Dimension >::get(), homework_06::Matrix< T, DefaulValue, Dimension >::get_next_index(), homework_06::Matrix< T, DefaulValue, Dimension >::operator[](), homework_06::Matrix< T, DefaulValue, Dimension >::set(), and homework_06::Matrix< T, DefaulValue, Dimension >::set().
size_
template<typename T , T DefaulValue = 0, std::size_t Dimension = 2> std::size_t homework_06::Matrix< T, DefaulValue, Dimension >::size_ = 0 private
Definition at line 559 of file matrix.hpp.
Referenced by homework_06::Matrix< T, DefaulValue, Dimension >::set(), homework_06::Matrix< T, DefaulValue, Dimension >::set(), and homework_06::Matrix< T, DefaulValue, Dimension >::size().
The documentation for this class was generated from the following file:
homework-06/matrix.hpp