Otus: homework_07::BulkParser Class Reference
homework_07::BulkParser Class Reference
#include <bulk.h>
Public Member Functions
BulkParser (std::size_t block_size=3)
void Run ()
void AppendBulkExecutor (BulkExecutorPtr bulk_executor)
template<typename T >
void AppendBulkExecutor ()
unsigned long long GetCommandTimestamp () const
const std::vector< std::string > & GetCommands () const
Private Member Functions
void ExecuteAndFlushCommands ()
Private Attributes
const std::size_t block_size_
std::vector< BulkExecutorPtr > bulk_executors_
bool eof_ = false
std::vector< std::string > commands_
unsigned long long command_timestamp_ = 0
int block_counter_ = 0
std::map< std::string, std::function< void()> > command_map_
Detailed Description
Definition at line 29 of file bulk.h.
Constructor & Destructor Documentation
BulkParser()
homework_07::BulkParser::BulkParser (std::size_t block_size = 3)
Definition at line 10 of file bulk.cpp.
  : block_size_(block_size) {
  command_map_ = {
    {"{", [this] {
      ++block_counter_;
      if (block_counter_ == 1) {
        ExecuteAndFlushCommands();
      }
    }},
    {"}", [this] {
      --block_counter_;
      if (block_counter_ == 0) {
        ExecuteAndFlushCommands();
      }
      block_counter_ = std::max(0, block_counter_);
    }},
    {"EOF", [this] {
      if (block_counter_ == 0) {
        ExecuteAndFlushCommands();
      }
      eof_ = true;
    }},
  };
}
Member Function Documentation
AppendBulkExecutor() [1/2]
template<typename T > void homework_07::BulkParser::AppendBulkExecutor () inline
Definition at line 36 of file bulk.h.
{
    AppendBulkExecutor(std::make_shared<T>());
  }
Referenced by AppendBulkExecutor().
AppendBulkExecutor() [2/2]
void homework_07::BulkParser::AppendBulkExecutor (BulkExecutorPtr bulk_executor)
Definition at line 69 of file bulk.cpp.
{
  bulk_executors_.emplace_back(bulk_executor);
}
ExecuteAndFlushCommands()
void homework_07::BulkParser::ExecuteAndFlushCommands () private
Definition at line 36 of file bulk.cpp.
{
  if (commands_.empty()) {
    return;
  }
  for (auto& executor : bulk_executors_) {
    executor->AcceptCommand(*this);
  }
  commands_.clear();
}
Referenced by BulkParser(), and Run().
GetCommands()
const std::vector< std::string > & homework_07::BulkParser::GetCommands () const
Definition at line 77 of file bulk.cpp.
{
  return commands_;
}
Referenced by homework_07::BulkPrinter::AcceptCommand(), and homework_07::BulkFileWriter::AcceptCommand().
GetCommandTimestamp()
unsigned long long homework_07::BulkParser::GetCommandTimestamp () const
Definition at line 73 of file bulk.cpp.
{
  return command_timestamp_;
}
Referenced by homework_07::BulkFileWriter::AcceptCommand().
Run()
void homework_07::BulkParser::Run ()
Definition at line 48 of file bulk.cpp.
                     {
  std::string cur_command;
  while(!eof_) {
    std::cin >> cur_command;
    auto command_it = command_map_.find(cur_command);
    if (command_it == command_map_.end()) {
      if (commands_.empty()) {
        command_timestamp_ = std::chrono::duration_cast<std::chrono::milliseconds>(
            std::chrono::system_clock::now().time_since_epoch()).count();
      }
      commands_.push_back(cur_command);
      if (commands_.size() >= block_size_ && block_counter_ == 0) {
        ExecuteAndFlushCommands();
      }
    } else {
      command_it->second();
    }
  }
}
Member Data Documentation
block_counter_
int homework_07::BulkParser::block_counter_ = 0 private
Definition at line 51 of file bulk.h.
Referenced by BulkParser(), and Run().
block_size_
const std::size_t homework_07::BulkParser::block_size_ private
Definition at line 46 of file bulk.h.
Referenced by Run().
bulk_executors_
std::vector<BulkExecutorPtr> homework_07::BulkParser::bulk_executors_ private
Definition at line 47 of file bulk.h.
Referenced by AppendBulkExecutor(), and ExecuteAndFlushCommands().
command_map_
std::map<std::string, std::function<void()> > homework_07::BulkParser::command_map_ private
Definition at line 52 of file bulk.h.
Referenced by BulkParser(), and Run().
command_timestamp_
unsigned long long homework_07::BulkParser::command_timestamp_ = 0 private
Definition at line 50 of file bulk.h.
Referenced by GetCommandTimestamp(), and Run().
commands_
std::vector<std::string> homework_07::BulkParser::commands_ private
Definition at line 49 of file bulk.h.
Referenced by ExecuteAndFlushCommands(), GetCommands(), and Run().
eof_
bool homework_07::BulkParser::eof_ = false private
Definition at line 48 of file bulk.h.
Referenced by BulkParser(), and Run().
The documentation for this class was generated from the following files:
homework-07/bulk.h
homework-07/bulk.cpp