Otus: homework_05::YamlComponentSerializer Class Reference
homework_05::YamlComponentSerializer Class Reference abstract
Public Member Functions
virtual YAML::Node Serialize (ComponentPtr component) const
virtual ComponentPtr ParseComponent (const YAML::Node &node) const =0
Static Public Member Functions
static std::string GetType (const YAML::Node &node)
Detailed Description
Definition at line 13 of file yaml_entity_component_serializer.cpp.
Member Function Documentation
GetType()
static std::string homework_05::YamlComponentSerializer::GetType (const YAML::Node & node) inline static
Definition at line 24 of file yaml_entity_component_serializer.cpp.
{
    auto type_node = node["type"];
    if (!type_node) {
      return std::string();
    }
    return type_node.as<std::string>();
  }
Referenced by homework_05::YamlEntityComponentSerializer::LoadEntities().
ParseComponent()
virtual ComponentPtr homework_05::YamlComponentSerializer::ParseComponent (const YAML::Node & node) const pure virtual
Implemented in homework_05::NameComponentSerializer, homework_05::Coordinate2DComponentSerializer, homework_05::CircleComponentSerializer, and homework_05::RectangleComponentSerializer.
Serialize()
virtual YAML::Node homework_05::YamlComponentSerializer::Serialize (ComponentPtr component) const inline virtual
Reimplemented in homework_05::NameComponentSerializer, homework_05::Coordinate2DComponentSerializer, homework_05::RectangleComponentSerializer, and homework_05::CircleComponentSerializer.
Definition at line 15 of file yaml_entity_component_serializer.cpp.
{
    YAML::Node component_node;
    component_node["type"] = component->GetComponentName().data();
    return component_node;
  }
Referenced by homework_05::NameComponentSerializer::Serialize(), homework_05::Coordinate2DComponentSerializer::Serialize(), homework_05::RectangleComponentSerializer::Serialize(), and homework_05::CircleComponentSerializer::Serialize().
The documentation for this class was generated from the following file:
homework-05/yaml_entity_component_serializer.cpp