Otus: homework_06 Namespace Reference
homework_06 Namespace Reference
Classes
class Matrix
class MatrixConstIterator
class MatrixHolder
class MatrixIterator
class TypeDeclarator
class ValueHolder
class ValueHolderViewBase
Functions
template<typename Array , std::size_t... I>
auto a2t_impl (const Array &a, std::index_sequence< I... >)
template<typename T , std::size_t N, typename Indices = std::make_index_sequence<N>>
auto a2t (const std::array< T, N > &a)
Function Documentation
a2t()
template<typename T , std::size_t N, typename Indices = std::make_index_sequence<N>> auto homework_06::a2t (const std::array< T, N > & a)
Definition at line 16 of file matrix.hpp.
{
  return a2t_impl(a, Indices{});
}
Referenced by homework_06::MatrixIterator< T, DefaulValue, Dimension >::operator*(), and homework_06::MatrixConstIterator< T, DefaulValue, Dimension >::operator*().
a2t_impl()
template<typename Array , std::size_t... I> auto homework_06::a2t_impl (const Array & a, std::index_sequence< I... >)
Definition at line 11 of file matrix.hpp.
{
  return std::make_tuple(a[I]...);
}
Referenced by a2t().