Otus: homework_08 Namespace Reference
homework_08 Namespace Reference
Classes
class Bayan
struct FileChunkInfo
class HashValue
Typedefs
using HashFunction = std::function< HashValue(const std::vector< char > &)>
Functions
std::optional< HashValue > ScanChunk (const std::filesystem::path &path, std::size_t block_size, std::size_t block_index, const HashFunction &hasher)
void ScanChunkInfo (FileChunkInfo &chunk_info, std::size_t block_size, std::size_t block_index, const HashFunction &hasher)
void ExtractBayanFiles (const FileChunkInfo &chunk_info, std::vector< std::set< std::filesystem::path > > &bayans, bool is_root_chunk=false)
HashValue Crc32Hash (const std::vector< char > &chunk)
HashValue Md5Hash (const std::vector< char > &chunk)
Typedef Documentation
HashFunction
using homework_08::HashFunction = typedef std::function<HashValue(const std::vector<char>&)>
Definition at line 211 of file bayan.cpp.
Function Documentation
Crc32Hash()
HashValue homework_08::Crc32Hash (const std::vector< char > & chunk)
Definition at line 280 of file bayan.cpp.
{
  boost::crc_32_type result;
  result.process_bytes(chunk.data(), chunk.size());
  return HashValue({result.checksum()});
}
Referenced by homework_08::Bayan::Scan().
ExtractBayanFiles()
void homework_08::ExtractBayanFiles (const FileChunkInfo & chunk_info, std::vector< std::set< std::filesystem::path > > & bayans, bool is_root_chunk = false)
Definition at line 265 of file bayan.cpp.
{
  if (chunk_info.child_chunks.empty() && !is_root_chunk) {
    bayans.push_back(chunk_info.paths);
    return;
  }
  for (const auto& child_chunk_pair : chunk_info.child_chunks) {
    ExtractBayanFiles(child_chunk_pair.second, bayans, false);
  }
}
Referenced by ExtractBayanFiles(), and homework_08::Bayan::Scan().
Md5Hash()
HashValue homework_08::Md5Hash (const std::vector< char > & chunk)
Definition at line 287 of file bayan.cpp.
{
  boost::uuids::detail::md5 hash;
  boost::uuids::detail::md5::digest_type digest;
  hash.process_bytes(chunk.data(), chunk.size());
  hash.get_digest(digest);
  return HashValue({
    digest[0],
    digest[1],
    digest[2],
    digest[3],
  });
}
Referenced by homework_08::Bayan::Scan().
ScanChunk()
std::optional< HashValue > homework_08::ScanChunk (const std::filesystem::path & path, std::size_t block_size, std::size_t block_index, const HashFunction & hasher)
Definition at line 213 of file bayan.cpp.
{
  if (block_size == 0) {
    return std::nullopt;
  }
  std::ifstream is{path, std::ios::in | std::ios::binary | std::ios::ate};
  std::size_t file_size = static_cast<std::size_t>(is.tellg());
  std::size_t cur_pos = block_size * block_index;
  if (cur_pos >= file_size) {
    return std::nullopt;
  }
  std::vector<char> chunk(block_size);
  is.seekg(cur_pos, is.beg);
  std::size_t chunk_end = block_size * (block_index + 1);
  std::size_t read_len = cur_pos + block_size > file_size ? file_size - cur_pos : block_size;
  is.read(chunk.data(), read_len);
  return hasher(chunk);
}
Referenced by ScanChunkInfo().
ScanChunkInfo()
void homework_08::ScanChunkInfo (FileChunkInfo & chunk_info, std::size_t block_size, std::size_t block_index, const HashFunction & hasher)
Definition at line 238 of file bayan.cpp.
{
  auto& child_chunks = chunk_info.child_chunks;
  for (const auto& path : chunk_info.paths) {
    auto hash_info = ScanChunk(path, block_size, block_index, hasher);
    if (!hash_info) {
      continue;
    }
    auto& child_chunk = child_chunks[hash_info.value()];
    child_chunk.paths.insert(path);
  }
  for (auto it = child_chunks.begin(); it != child_chunks.end();) {
    if (it->second.paths.size() < 2) {
      it = child_chunks.erase(it);
    } else {
      ScanChunkInfo(it->second, block_size, block_index + 1, hasher);
      ++it;
    }
  }
}
Referenced by homework_08::Bayan::Scan(), and ScanChunkInfo().