Otus: homework_05::ConsoleToolset Class Reference
homework_05::ConsoleToolset Class Reference
#include <console_toolset.h>
Public Member Functions
ConsoleToolset ()
void Draw (const EditorWeakPtr &editor) override
void ImportDocument (const EditorWeakPtr &editor) override
void ExportDocument (const EditorWeakPtr &editor) override
void DrawShapes (const EditorWeakPtr &editor) override
void EditShape (EntityWeakPtr entity) override
template<typename... Ts>
void Request (const std::string &request_text, Ts &... values)
template<typename... Ts>
void Print (Ts &&... values)
Static Public Attributes
static constexpr std::string_view kSingleSeparator = "---------------------------------------"
static constexpr std::string_view kDoubleSeparator = "======================================="
Protected Member Functions
void DrawShape (EntityWeakPtr entity) override
Protected Member Functions inherited from homework_05::Toolset
ComponentHandlerWeakPtr GetComponentHandler (ComponentWeakPtr component) const
Private Member Functions
void CreateActions ()
void RequestAction (const struct ActionContext &context)
Private Attributes
ConsoleActionPtr root_action_
Additional Inherited Members
Protected Attributes inherited from homework_05::Toolset
ComponentHandlerFactoryPtr component_handler_factory_
Detailed Description
Definition at line 12 of file console_toolset.h.
Constructor & Destructor Documentation
ConsoleToolset()
homework_05::ConsoleToolset::ConsoleToolset ()
Definition at line 80 of file console_toolset.cpp.
{
  component_handler_factory_ = std::make_shared<ConsoleComponentHandlerFactory>();
  CreateActions();
}
Member Function Documentation
CreateActions()
void homework_05::ConsoleToolset::CreateActions () private
Definition at line 85 of file console_toolset.cpp.
{
  root_action_ = std::make_shared<ConsoleAction>("Main menu");
  auto new_document = std::make_shared<ConsoleAction>("New document");
  auto import_document = std::make_shared<ConsoleAction>("Import document");
  auto export_document = std::make_shared<ConsoleAction>("Export document");
  auto draw_all = std::make_shared<ConsoleAction>("Draw all");
  auto add_shape = std::make_shared<ConsoleAction>("Add shape");
  auto remove_shape = std::make_shared<ConsoleAction>("Remove shape");
  auto quit_action = std::make_shared<ConsoleAction>("Quit");
  root_action_->AppendChild(new_document);
  root_action_->AppendChild(import_document);
  root_action_->AppendChild(export_document);
  root_action_->AppendChild(draw_all);
  root_action_->AppendChild(add_shape);
  root_action_->AppendChild(remove_shape);
  root_action_->AppendChild(quit_action);
  quit_action->SetCallback([](const ActionContext& context) {
    context.editor.lock()->SetExit(true);
  });
  auto new_doc_yes = std::make_shared<ConsoleAction>("Yes");
  auto action_no = std::make_shared<ConsoleAction>("No");
  new_document->AppendChild(new_doc_yes);
  new_document->AppendChild(action_no);
  new_doc_yes->SetCallback([](const ActionContext& context) {
    context.editor.lock()->NewDocument();
    std::cout << "New document created!\n";
  });
  auto import_doc_yes = std::make_shared<ConsoleAction>("Confirm import");
  import_doc_yes->SetCallback([](const ActionContext& context) {
    context.toolset.lock()->ImportDocument(context.editor);
  });
  import_document->AppendChild(import_doc_yes);
  import_document->AppendChild(action_no);
  auto export_doc_yes = std::make_shared<ConsoleAction>("Confirm export");
  export_doc_yes->SetCallback([](const ActionContext& context) {
    context.toolset.lock()->ExportDocument(context.editor);
  });
  export_document->AppendChild(export_doc_yes);
  export_document->AppendChild(action_no);
  draw_all->SetCallback([](const ActionContext& context) {
    context.toolset.lock()->DrawShapes(context.editor);
  });
  auto add_circle = std::make_shared<ConsoleAction>("Add circle");
  add_circle->SetCallback([](const ActionContext& context) {
    auto circle = context.editor.lock()->AppendCircle();
    context.toolset.lock()->EditShape(circle);
  });
  auto add_rectangle = std::make_shared<ConsoleAction>("Add rectangle");
  add_rectangle->SetCallback([](const ActionContext& context) {
    auto rectangle = context.editor.lock()->AppendRectangle();
    context.toolset.lock()->EditShape(rectangle);
  });
  auto cancel = std::make_shared<ConsoleAction>("Cancel");
  add_shape->AppendChild(add_circle);
  add_shape->AppendChild(add_rectangle);
  add_shape->AppendChild(cancel);
  auto confirm_remove = std::make_shared<ConsoleAction>("Confirm remove shape");
  remove_shape->AppendChild(confirm_remove);
  remove_shape->AppendChild(cancel);
  confirm_remove->SetCallback([](const ActionContext& context) {
    std::cout << "Enter shape id: ";
    EnityId id;
    std::cin >> id;
    bool removed = context.editor.lock()->RemoveEnity(id);
    if (removed) {
      std::cout << "Enity [" << id << "] has been removed!\n";
    } else {
      std::cout << "Cannot remove entity " << id << "\n";
    }
  });
}
Referenced by ConsoleToolset().
Draw()
void homework_05::ConsoleToolset::Draw (const EditorWeakPtr & editor) override virtual
Implements homework_05::Toolset.
Definition at line 208 of file console_toolset.cpp.
{
  ActionContext context;
  context.editor = editor;
  context.toolset = shared_from_this();
  RequestAction(context);
}
DrawShape()
void homework_05::ConsoleToolset::DrawShape (EntityWeakPtr entity) override protected virtual
Implements homework_05::Toolset.
Definition at line 222 of file console_toolset.cpp.
{
  std::cout << ConsoleToolset::kSingleSeparator << "\n";
  auto entity_ptr = entity.lock();
  std::cout << "Shape id: " << entity_ptr->GetId() << "\n";
  const auto& compoenents = entity_ptr->GetComponents();
  auto this_ptr = shared_from_this();
  for (const auto& component : compoenents) {
    auto handler = GetComponentHandler(component);
    handler.lock()->DrawProperties(component, this_ptr);
  }
  std::cout << ConsoleToolset::kSingleSeparator << "\n";
}
DrawShapes()
void homework_05::ConsoleToolset::DrawShapes (const EditorWeakPtr & editor) override virtual
Reimplemented from homework_05::Toolset.
Definition at line 215 of file console_toolset.cpp.
{
  std::cout << ConsoleToolset::kSingleSeparator << "\n";
  std::cout << "Shape list:\n";
  Toolset::DrawShapes(editor);
}
EditShape()
void homework_05::ConsoleToolset::EditShape (EntityWeakPtr entity) override virtual
Implements homework_05::Toolset.
Definition at line 235 of file console_toolset.cpp.
{
  auto entity_ptr = entity.lock();
  const auto& compoenents = entity_ptr->GetComponents();
  auto this_ptr = shared_from_this();
  for (const auto& component : compoenents) {
    auto handler = GetComponentHandler(component);
    handler.lock()->SetProperties(component, this_ptr);
  }
  std::cout << ConsoleToolset::kSingleSeparator << "\n";
}
Referenced by CreateActions().
ExportDocument()
void homework_05::ConsoleToolset::ExportDocument (const EditorWeakPtr & editor) override virtual
Implements homework_05::Toolset.
Definition at line 191 of file console_toolset.cpp.
{
  std::string export_filename;
  std::cout << "Enter document filename: ";
  std::cin >> export_filename;
  try {
    bool res = editor.lock()->ExportDocument(kYamlSerializerDescription, export_filename);
    if (res) {
      std::cout << "Documment '" << export_filename << "' has been exported!\n";
    } else {
      std::cout << "Cannot export '" << export_filename << "'!\n";
    }
  } catch (std::exception& ex) {
    std::cout << "Cannot export '" << export_filename << "' by reason:\n";
    std::cout << ex.what() << "\n";
  }
}
Referenced by CreateActions().
ImportDocument()
void homework_05::ConsoleToolset::ImportDocument (const EditorWeakPtr & editor) override virtual
Implements homework_05::Toolset.
Definition at line 174 of file console_toolset.cpp.
{
  std::string import_filename;
  std::cout << "Enter document filename: ";
  std::cin >> import_filename;
  try {
    bool res = editor.lock()->ImportDocument(kYamlSerializerDescription, import_filename);
    if (res) {
      std::cout << "Documment '" << import_filename << "' has been imported!\n";
    } else {
      std::cout << "Cannot import '" << import_filename << "'!\n";
    }
  } catch (std::exception& ex) {
    std::cout << "Cannot import '" << import_filename << "' by reason:\n";
    std::cout << ex.what() << "\n";
  }
}
Referenced by CreateActions().
Print()
template<typename... Ts> void homework_05::ConsoleToolset::Print (Ts &&... values) inline
Definition at line 31 of file console_toolset.h.
{
    ((std::cout << std::forward<Ts>(values)), ...);
    std::cout << "\n";
  }
Request()
template<typename... Ts> void homework_05::ConsoleToolset::Request (const std::string & request_text, Ts &... values) inline
Definition at line 25 of file console_toolset.h.
{
    std::cout << request_text;
    ((std::cin >> (values)), ...);
  }
RequestAction()
void homework_05::ConsoleToolset::RequestAction (const struct ActionContext & context) private
Definition at line 170 of file console_toolset.cpp.
{
  root_action_->Request(context);
}
Referenced by Draw().
Member Data Documentation
kDoubleSeparator
constexpr std::string_view homework_05::ConsoleToolset::kDoubleSeparator = "=======================================" static constexpr
Definition at line 22 of file console_toolset.h.
Referenced by homework_05::ConsoleAction::Request().
kSingleSeparator
constexpr std::string_view homework_05::ConsoleToolset::kSingleSeparator = "---------------------------------------" static constexpr
Definition at line 21 of file console_toolset.h.
Referenced by DrawShape(), DrawShapes(), EditShape(), and homework_05::ConsoleAction::Request().
root_action_
ConsoleActionPtr homework_05::ConsoleToolset::root_action_ private
Definition at line 43 of file console_toolset.h.
Referenced by CreateActions(), and RequestAction().
The documentation for this class was generated from the following files:
homework-05/console_toolset.h
homework-05/console_toolset.cpp