Otus: homework_05::EntityFactory Class Reference
homework_05::EntityFactory Class Reference
#include <entity_factory.h>
Static Public Member Functions
static EntityPtr CreateDefaultCircle (unsigned int id)
static EntityPtr CreateDefaultRectangle (unsigned int id)
static void SetEntityName (EntityPtr entity, const std::string &name)
Static Private Member Functions
static EntityPtr CreateDefaultShape (unsigned int id)
Detailed Description
Definition at line 9 of file entity_factory.h.
Member Function Documentation
CreateDefaultCircle()
EntityPtr homework_05::EntityFactory::CreateDefaultCircle (unsigned int id) static
Definition at line 16 of file entity_factory.cpp.
{
  auto default_circle = EntityFactory::CreateDefaultShape(id);
  default_circle->AddComponent(std::make_shared<CircleComponent>());
  return default_circle;
}
Referenced by homework_05::Editor::AppendCircle().
CreateDefaultRectangle()
EntityPtr homework_05::EntityFactory::CreateDefaultRectangle (unsigned int id) static
Definition at line 23 of file entity_factory.cpp.
{
  auto default_rectangle = EntityFactory::CreateDefaultShape(id);
  default_rectangle->AddComponent(std::make_shared<RectangleComponent>());
  return default_rectangle;
}
Referenced by homework_05::Editor::AppendRectangle().
CreateDefaultShape()
EntityPtr homework_05::EntityFactory::CreateDefaultShape (unsigned int id) static private
Definition at line 8 of file entity_factory.cpp.
{
  auto default_shape = std::make_shared<Entity>(id);
  auto coordinate_component = std::make_shared<Coordinate2DComponent>();
  default_shape->AddComponent(coordinate_component);
  return default_shape;
}
Referenced by CreateDefaultCircle(), and CreateDefaultRectangle().
SetEntityName()
void homework_05::EntityFactory::SetEntityName (EntityPtr entity, const std::string & name) static
Definition at line 30 of file entity_factory.cpp.
{
  std::shared_ptr<NameComponent> name_component;
  const auto& components = entity->GetComponents();
  for (auto& component : components) {
    if (component->GetComponentName() == NameComponent::kComponentName) {
      name_component = std::static_pointer_cast<NameComponent>(component);
      break;
    }
  }
  if (!name_component) {
    name_component = std::make_shared<NameComponent>();
    entity->AddComponent(name_component);
  }
  name_component->SetName(name);
}
The documentation for this class was generated from the following files:
homework-05/entity_factory.h
homework-05/entity_factory.cpp