Otus: homework_09 Namespace Reference
homework_09 Namespace Reference
Classes
struct BulkContext
class CommandExecutor
class ExecutorBase
struct ExecutorContent
class ExecutorFileWriter
class ExecutorHandler
class ExecutorLogger
Typedefs
using ExecutorContentContainer = std::list< std::shared_ptr< ExecutorContent > >
Functions
uint32_t connect (uint32_t block_size)
void receive (const char *buffer, uint32_t buffer_size, uint32_t context_id)
void disconnect (uint32_t context_id)
Variables
uint32_t context_couter = 0
std::map< uint32_t, BulkContext > context
std::shared_mutex context_mutex
homework_09::ExecutorHandler executor_handler
Typedef Documentation
ExecutorContentContainer
using homework_09::ExecutorContentContainer = typedef std::list<std::shared_ptr<ExecutorContent> >
Definition at line 32 of file bulk.h.
Function Documentation
connect()
uint32_t homework_09::connect (uint32_t block_size)
Definition at line 15 of file async.cpp.
{
  std::lock_guard<std::shared_mutex> lock_write(context_mutex);
  ++context_couter;
  context.emplace(context_couter, BulkContext(block_size));
  return context_couter;
}
Referenced by test1(), test2(), and test3().
disconnect()
void homework_09::disconnect (uint32_t context_id)
Definition at line 35 of file async.cpp.
{
  std::lock_guard<std::shared_mutex> lock_write(context_mutex);
  auto context_it = context.find(context_id);
  if (context_it != context.end()) {
    context.erase(context_it);
  }
}
Referenced by test1(), test2(), and test3().
receive()
void homework_09::receive (const char * buffer, uint32_t buffer_size, uint32_t context_id)
Definition at line 22 of file async.cpp.
{
  std::shared_lock<std::shared_mutex> lock_read(context_mutex);
  auto context_it = context.find(context_id);
  if (context_it == context.end()) {
    return;
  }
  homework_09::CommandExecutor::ExecuteCommand(
    std::string(buffer, buffer + buffer_size),
    context_it->second,
    executor_handler);
}
Referenced by test1(), test2(), and test3().
Variable Documentation
context
std::map<uint32_t, BulkContext> homework_09::context
Definition at line 11 of file async.cpp.
Referenced by connect(), disconnect(), and receive().
context_couter
uint32_t homework_09::context_couter = 0
Definition at line 10 of file async.cpp.
Referenced by connect().
context_mutex
std::shared_mutex homework_09::context_mutex
Definition at line 12 of file async.cpp.
Referenced by connect(), disconnect(), and receive().
executor_handler
homework_09::ExecutorHandler homework_09::executor_handler
Definition at line 13 of file async.cpp.
Referenced by homework_09::CommandExecutor::ExecuteCommand(), and receive().