Otus: homework_05::Toolset Class Reference
homework_05::Toolset Class Reference abstract
#include <toolset.h>
Public Member Functions
virtual void Draw (const EditorWeakPtr &editor)=0
virtual void ImportDocument (const EditorWeakPtr &editor)=0
virtual void ExportDocument (const EditorWeakPtr &editor)=0
virtual void EditShape (EntityWeakPtr entity)=0
virtual void DrawShapes (const EditorWeakPtr &editor)
Protected Member Functions
virtual void DrawShape (EntityWeakPtr entity)=0
ComponentHandlerWeakPtr GetComponentHandler (ComponentWeakPtr component) const
Protected Attributes
ComponentHandlerFactoryPtr component_handler_factory_
Private Attributes
std::unordered_map< std::string_view, ComponentHandlerPtr > component_handlers_
Detailed Description
Definition at line 10 of file toolset.h.
Member Function Documentation
Draw()
virtual void homework_05::Toolset::Draw (const EditorWeakPtr & editor) pure virtual
Implemented in homework_05::ConsoleToolset.
DrawShape()
virtual void homework_05::Toolset::DrawShape (EntityWeakPtr entity) protected pure virtual
Implemented in homework_05::ConsoleToolset.
Referenced by DrawShapes().
DrawShapes()
void homework_05::Toolset::DrawShapes (const EditorWeakPtr & editor) virtual
Reimplemented in homework_05::ConsoleToolset.
Definition at line 21 of file toolset.cpp.
{
  const auto& entities = editor.lock()->GetEntities();
  for ([[maybe_unused]] const auto& [id, entity] : entities) {
    DrawShape(entity);
  }
}
Referenced by homework_05::ConsoleToolset::DrawShapes().
EditShape()
virtual void homework_05::Toolset::EditShape (EntityWeakPtr entity) pure virtual
Implemented in homework_05::ConsoleToolset.
ExportDocument()
virtual void homework_05::Toolset::ExportDocument (const EditorWeakPtr & editor) pure virtual
Implemented in homework_05::ConsoleToolset.
GetComponentHandler()
ComponentHandlerWeakPtr homework_05::Toolset::GetComponentHandler (ComponentWeakPtr component) const protected
Definition at line 8 of file toolset.cpp.
{
  auto component_ptr = component.lock();
  auto it = component_handlers_.find(component_ptr->GetComponentName());
  if (it != component_handlers_.end()) {
    return it->second;
  }
  auto handler = component_ptr->CreateHandler(component_handler_factory_);
  component_handlers_[component_ptr->GetComponentName()] = handler;
  return handler;
}
Referenced by homework_05::ConsoleToolset::DrawShape(), and homework_05::ConsoleToolset::EditShape().
ImportDocument()
virtual void homework_05::Toolset::ImportDocument (const EditorWeakPtr & editor) pure virtual
Implemented in homework_05::ConsoleToolset.
Member Data Documentation
component_handler_factory_
ComponentHandlerFactoryPtr homework_05::Toolset::component_handler_factory_ protected
Definition at line 23 of file toolset.h.
Referenced by homework_05::ConsoleToolset::ConsoleToolset(), and GetComponentHandler().
component_handlers_
std::unordered_map<std::string_view, ComponentHandlerPtr> homework_05::Toolset::component_handlers_ mutable private
Definition at line 26 of file toolset.h.
Referenced by GetComponentHandler().
The documentation for this class was generated from the following files:
homework-05/toolset.h
homework-05/toolset.cpp